[project]
name = "saga_json"

[bin]
main = "src/Main.saga"

[library]
module = "SagaJson"
expose = ["SagaJson", "SagaJson.Encode", "SagaJson.Decode", "SagaJson.Codec", "SagaJson.Parser", "SagaJson.Mono"]
